version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/vibetalk.watchvaultbydiggie.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/vibetalk.watchvaultbydiggie.com/privkey.pem:/etc/nginx/ssl/privkey.pem
  web:
    image: htetlinmaung/vibetalk
    restart: always
    ports:
      - "3000:3000"
